name: eos_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  core:  
    path: ../packages/core
  dependencies:
    path: ../packages/dependencies
  commons:
    path: ../packages/commons  
  task_manager:
    path: ../packages/task_manager  

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

