name: task_manager
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  core:  
    path: ../core  
  commons:  
    path: ../commons    
  dependencies:  
    path: ../dependencies   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
  
