# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      flutter_version: ${{ steps.flutter.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
        id: flutter

      - name: Install dependencies
        run: |
          cd base_app && flutter pub get
          cd ../packages/commons && flutter pub get
          cd ../core && flutter pub get
          cd ../dependencies && flutter pub get
          cd ../task_manager && flutter pub get

  code_analyze:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Run flutter analyze
        run: flutter analyze

      - name: Dart format check
        run: dart fix --dry-run --set-exit-if-changed

      - name: Dart apply format
        run: dart fix --apply --set-exit-if-changed

  build_ios_debug:
    runs-on: macos-latest
    name: Build Flutter (iOS Debug)
    needs: code_analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: build iOS Debug
        run: |
          cd base_app && flutter pub get
          cd base_app && flutter build ios --debug --no-codesign

  build_appbundle_debug:
    runs-on: ubuntu-latest
    name: Build Flutter (Android Debug)
    needs: code_analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: build Android Debug
        run: |
          cd base_app && flutter pub get
          cd base_app && flutter build appbundle --debug

      - name: Upload App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: appbundle-debug
          path: base_app/build/app/outputs/bundle/debug/app-debug.aab
