# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code_analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with: 
          channel: 'stable'
      
      - name: Run flutter clean
        run: flutter clean    
     
      - name: Install dependencies
        run: flutter pub get    

      - name: Run flutter analyze
        run: flutter analyze
      
      - name: Dart format
        run: dart fix --dry-run --set-exit-if-changed-lib/
     
      - name: Dart apply format
        run:  dart fix --apply --set-exit-if-changed-lib/
  
  build_ios_debug:
    runs-on: macos-latest
    name: build Flutter (IOS Debug)
    needs: [code_analyze]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with: 
          channel: 'stable'    
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign      
  
  build_ios_release:
    runs-on: macos-latest
    name: build Flutter (IOS Release)
    needs: [code_analyze, build_ios_debug]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with: 
          channel: 'stable'    
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign

  build_appbundle_debug:
    runs-on: ubuntu-latest
    name: build Flutter (Android Debug)
    needs: [code_analyze]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with: 
          channel: 'stable'    
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build appbundle --debug
      - name: Upload appbundle
        uses: actions/upload-artifact@v3
        with: 
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
